type postUsuarioSolusInputDto = {
    fone_agendamento?: string,
    id_ambulatorio: number,
    id_prestador: number,
    email_beneficiario?: string,
    nnumeusua: number,
    observacao: string,
    nnumeespec: number,
    criado_por?: number,
    nnumeguia?: number,
    nriscguia: number,
    nuintguia?: number,
    npesoguia?: number,
    naltuguia?: number,
    ntempguia?: number,
    nfcarguia?: number,
    nfresguia?: number,
    nsto2guia?: number,
    npamaguia?: number,
    npamiguia?: number,
    nhgt_guia?: number,
    chgt_guia?: string,
    ncabdguia?: number,
    npcefguia?: number,
    cnomeusua?: string,
    cncomusua?: string,
    cttpdguia?: string,
    chipoguia?: string,
    ntpdoguia?: number,
    cobpaobspa?: string,
    nr_sequencia?: number,
    perfil: boolean | undefined,
}

export type { postUsuarioSolusInputDto }